### PR TITLE
chore: Adding feedback request to contributors bot

### PR DESCRIPTION
**Pull request by joethreepwood**
I've seen good response rates asking contributors for feedback via G2. 

However, this is tricky as it's manual and not all of them are in the Slack. 

Solution: Add a simple request to the bot, which tags them when recognizing their work. 

Added bonus: +1 to the number of repos I have touched at PostHog so far!

### CODE REVIEW

**Review by yakkomajuri — APPROVED** [review]
feels a bit too pushy on the open source community but happy to help other teams if this was decided

**Comment by joethreepwood** [comment]
I don't feel it's too pushy personally, but want to be mindful to this feedback. I'll open it as a question and see if others' feel strongly before merging. Thanks Yakko!

**Comment by mariusandra** [comment]
I feel "let us know what you think" is perfectly great, but "submit a review about us on trustpilot" (or any other website) to be kind of pushy by nature.

**Comment by charlescook-ph** [comment]
Agree - 'let us know what you think' is fine with me, but it feels like a bait-and-switch to ask that and then direct people to an external site that hoovers up their personal data (this is mainly why I ignore any feedback requests from products unless they go to the company directly).

**Comment by joethreepwood** [comment]
OK, it's been consistent feedback that this feels too pushy, even with the softened wording. I'm going to close this, unmerged.

**Pull request closed without merging**
